// This file will be auto-generated by Supabase CLI
// Run: pnpm db:gen-types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// Placeholder types until Supabase generates them
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          role: "admin" | "driver" | "customer";
          full_name: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          role?: "admin" | "driver" | "customer";
          full_name?: string | null;
          avatar_url?: string | null;
        };
        Update: {
          role?: "admin" | "driver" | "customer";
          full_name?: string | null;
          avatar_url?: string | null;
        };
      };
      bins: {
        Row: {
          id: string;
          location: unknown; // PostGIS geography
          address: string;
          capacity_liters: number;
          waste_type: "general" | "recycling" | "organic" | "hazardous";
          status: "active" | "damaged" | "maintenance_required";
          fill_level: number;
          battery_level: number;
          last_pickup: string | null;
          predicted_full: string | null;
          sensor_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          location: unknown;
          address: string;
          capacity_liters?: number;
          waste_type?: "general" | "recycling" | "organic" | "hazardous";
          status?: "active" | "damaged" | "maintenance_required";
          fill_level?: number;
          battery_level?: number;
          sensor_id: string;
        };
        Update: {
          location?: unknown;
          address?: string;
          capacity_liters?: number;
          waste_type?: "general" | "recycling" | "organic" | "hazardous";
          status?: "active" | "damaged" | "maintenance_required";
          fill_level?: number;
          battery_level?: number;
          last_pickup?: string | null;
          sensor_id?: string;
        };
      };
      sensor_readings: {
        Row: {
          id: number;
          bin_id: string;
          fill_level: number;
          battery_level: number;
          timestamp: string;
        };
        Insert: {
          bin_id: string;
          fill_level: number;
          battery_level: number;
        };
        Update: never;
      };
      routes: {
        Row: {
          id: string;
          driver_id: string;
          status: "pending" | "in_progress" | "completed";
          scheduled_date: string;
          stops: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          driver_id: string;
          status?: "pending" | "in_progress" | "completed";
          scheduled_date: string;
          stops?: Json;
        };
        Update: {
          driver_id?: string;
          status?: "pending" | "in_progress" | "completed";
          scheduled_date?: string;
          stops?: Json;
        };
      };
      pickups: {
        Row: {
          id: string;
          route_id: string;
          bin_id: string;
          driver_id: string;
          order_index: number;
          status: "pending" | "collected" | "skipped";
          collected_at: string | null;
          fill_level_at_pickup: number | null;
          photo_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          route_id: string;
          bin_id: string;
          driver_id: string;
          order_index: number;
          status?: "pending" | "collected" | "skipped";
        };
        Update: {
          status?: "pending" | "collected" | "skipped";
          collected_at?: string | null;
          fill_level_at_pickup?: number | null;
          photo_url?: string | null;
        };
      };
      issues: {
        Row: {
          id: string;
          reported_by: string;
          bin_id: string;
          type: "overflow" | "damage" | "missed";
          description: string;
          image_url: string | null;
          status: "open" | "resolved";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          reported_by: string;
          bin_id: string;
          type: "overflow" | "damage" | "missed";
          description: string;
          image_url?: string | null;
        };
        Update: {
          type?: "overflow" | "damage" | "missed";
          description?: string;
          image_url?: string | null;
          status?: "open" | "resolved";
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: "admin" | "driver" | "customer";
      waste_type: "general" | "recycling" | "organic" | "hazardous";
      bin_status: "active" | "damaged" | "maintenance_required";
      route_status: "pending" | "in_progress" | "completed";
      pickup_status: "pending" | "collected" | "skipped";
      issue_type: "overflow" | "damage" | "missed";
      issue_status: "open" | "resolved";
    };
  };
}

// Helper types for easier usage
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type InsertTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type UpdateTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
